os: linux

language: go

go:
    - 1.14.x
    
services:
    - postgresql
    - docker
    

before_script:
  - psql -c "CREATE DATABASE postgres;" -U postgres

script:
    # Test the code
    - go test -v ./...